### PR TITLE
Fixed assignment in if expression

### PR DESCRIPTION
**Pull request by dbrgn**
This could have been quite ugly, if this assignment were at another place.

Aren't any static code analysis tools used in the publication workflow of these libraries? I found this bug with ESLint. Especially with regard to authentication libraries, code quality needs to be high.

### CODE REVIEW

**Comment by erickoledadevrel** [comment]
Good catch, and no, I hadn't used any static code analysis before. Please sign the CLA and I'll merge.

**Comment by dbrgn** [comment]
I already did in 2013 :)

**Comment by erickoledadevrel** [comment]
Since it's a new email you'll need to sign it again. Please follow the links that googlebot provided above.

**Comment by dbrgn** [comment]
I don't have a Google account on that e-mail address, and I'm not willing to register a new Google account just so that I can sign the CLA. And apparently I can only sign the CLA with a Google account, is that correct? (At least I'm always redirected to the login age.)

If that's a problem for Google, then you can also close this pull request and fix it in a commit of your own. I don't care about the copyright of this commit, I release it under public domain. I just want this issue to be fixed.

**Comment by erickoledadevrel** [comment]
No need to make another Google account. An alternative option is to change the email used on your git commits to be the one we have a CLA for:

https://help.github.com/articles/setting-your-email-in-git/

That said, I'm happy to just make the fix myself.

**Comment by dbrgn** [comment]
OK, amended the commit. Still, it should be possible to sign the CLA without having a Google account.

**Comment by dbrgn** [comment]
Thx :)

**Pull request merged**
